In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[1,2,3],[1,2,3]])
print(b)

[[1 2 3]
 [1 2 3]]


In [7]:
#dimensions
b.ndim

2

In [8]:
#shape
a.shape

(3,)

In [10]:
#type
b.dtype

dtype('int32')

In [11]:
a.itemsize

4

In [12]:
#total size
a.size

3

In [14]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
#grt element[r,c]
a[1,5]

13

In [17]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [18]:
a[:,0]

array([1, 8])

In [21]:
a[0, 1:6:2]

array([2, 4, 6])

In [23]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [28]:
n=np.zeros((2,3))
print(n)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
n=np.ones((2,3))
print(n)

[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
n=np.random.rand(2,3)
print(n)

[[0.41223901 0.87316908 0.22308749]
 [0.01363779 0.50616013 0.66608448]]


In [33]:
n=np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
n=np.array(7)
print(n)

7


In [35]:
n=np.eye(3,k=-2)
print(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [37]:
a=[1,2,3,4,5,6]
n=np.reshape(a,(-1,2))
print(n)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
import numpy as np
a=np.array([i for i in range(0,5)])
print(type(a))

<class 'numpy.ndarray'>


In [15]:
b=np.array([1,2,3,4,5,6])

print(b)

[1 2 3 4 5 6]


In [11]:
a="""creating a vector( 1 d array) 
creating a matrix( 2d array)
sparse matrix
selecting elements
describing a matrix
applying operation to elements
finding the max and the minimum value
calculating avarage, variants and standard deviation

reshaping array
transposing a vector or a matrix
finding the determinant and rank of the matrix
geting the digonal of the matrix
calculating the trase of the matrix
finding eigen values and eigen vectors
calculating dot productes
adding, subtracting, and multiplying matrix
inverting a matix
generating random values

"""

    

In [17]:
a=np.reshape(b,(-1,2))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
array=np.random.rand(2,3)
print(array)

[[0.0933786  0.68016434 0.30257437]
 [0.16309247 0.32902504 0.45402104]]


In [23]:
d=np.array([[1,2,3],[4,5,6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [29]:
d[0:,1]

array([2, 5])

In [30]:
d[1:,0]

array([4])

In [32]:
d.max()

6

In [33]:
d.min()

1

In [42]:
a=np.eye(3,dtype="int32")
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.linalg.inv(a)
print(b)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [47]:
def transpose(A,B): 

	for i in range(N): 
		for j in range(N): 
			B[i][j] = A[j][i] 
A = [ [1, 1, 1, 1], 
	[2, 2, 2, 2], 
	[3, 3, 3, 3], 
	[4, 4, 4, 4]] 


B = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

transpose(A, B) 

print("Result matrix is") 
for i in range(N): 
	for j in range(N): 
		print(B[i][j], " ", end='') 
	print()

Result matrix is
1  2  3  4  
1  2  3  4  
1  2  3  4  
1  2  3  4  


In [50]:
a=d.diagonal()
print(a)

[1 5]


In [51]:
 import numpy as np 
from scipy.sparse import csr_matrix 
sparseMatrix = csr_matrix((3, 4), 
dtype = np.int8).toarray() 
print(sparseMatrix)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### creating vector(1 d array)

In [59]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### creating matrix(2d array)

In [55]:
import numpy as np
arr1=np.array([[1,2,3],[1,2,3]])
print(arr1)

[[1 2 3]
 [1 2 3]]


### transposing a vector or a matrix

In [57]:
print(arr1.T)

[[1 1]
 [2 2]
 [3 3]]


In [60]:
print(arr.T)

[1 2 3 4 5]


### max and min value in matrix

In [61]:
arr1.max()

3

In [62]:
arr1.min()

1

In [63]:
arr.max()

5

In [64]:
arr.min()

1

### geting the digonal of the matrix

In [66]:
di=np.array([[1,2,3],[4,5,6],[7,8,9]])
di.diagonal()

array([1, 5, 9])

### getting random values in array

In [71]:
ar=np.random.rand(2,3)
print(ar)

[[0.09128546 0.85703659 0.06847213]
 [0.57046244 0.28440801 0.68881617]]


### opreations of matrix

In [15]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

#addition

print(np.add(arr1,arr2))

#subtraction

print(np.subtract(arr1,arr2))

#divide

print(np.divide(arr1,arr2))

#multiply

print(np.multiply(arr1,arr2))

#dot

print(np.dot(arr1,arr2))

#square root

print(np.sqrt(arr1))
print(np.sqrt(arr2))


#sum of elements
print(np.sum(arr1))
print(np.sum(arr2))


#column wise sum
print(np.sum(arr2,axis=0))

#Tranprose of matrix
print(arr1.T)
print(arr2.T)


[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
32
[1.         1.41421356 1.73205081]
[2.         2.23606798 2.44948974]
6
15
15
[1 2 3]
[4 5 6]


In [18]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[5,3,4]])
arr2=np.array([[4,5,6],[7,8,9],[2,4,3]])

#addition

print(np.add(arr1,arr2))

#subtraction

print(np.subtract(arr1,arr2))

#divide

print(np.divide(arr1,arr2))

#multiply

print(np.multiply(arr1,arr2))

#dot

print(np.dot(arr1,arr2))

#square root

print(np.sqrt(arr1))
print(np.sqrt(arr2))


#sum of elements
print(np.sum(arr1))
print(np.sum(arr2))


#column wise sum
print(np.sum(arr2,axis=0))

#Tranprose of matrix
print(arr1.T)
print(arr2.T)


[[ 5  7  9]
 [11 13 15]
 [ 7  7  7]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 3 -1  1]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [2.5        0.75       1.33333333]]
[[ 4 10 18]
 [28 40 54]
 [10 12 12]]
[[24 33 33]
 [63 84 87]
 [49 65 69]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.23606798 1.73205081 2.        ]]
[[2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]
 [1.41421356 2.         1.73205081]]
33
48
[13 17 18]
[[1 4 5]
 [2 5 3]
 [3 6 4]]
[[4 7 2]
 [5 8 4]
 [6 9 3]]


### calculating avarage, variance and standard deviation

In [24]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.average(arr))

arr1=np.array([[1,2,8,4],[1,2,3,4]])
print(np.average(arr1))

2.5
3.125


### inverse matrix

In [27]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(np.linalg.inv(arr))


[[ 1.35107989e+16 -2.70215978e+16  1.35107989e+16]
 [-2.70215978e+16  5.40431955e+16 -2.70215978e+16]
 [ 1.35107989e+16 -2.70215978e+16  1.35107989e+16]]


### trace of matrix

In [33]:
arr=np.array([[1,2,3],[3,4,5],[5,6,7]])
a=arr.diagonal()
#a=np.array(a)
print(np.sum(a))

12
