In [4]:
import numpy as np
a=np.array([1,2,3,4])
print(a)


AttributeError: module 'numpy' has no attribute 'max'

In [6]:
np.array([3,4,5,6,])

AttributeError: module 'numpy' has no attribute 'max'

In [8]:
np.array([[1,3,3],[1,2,3]])

array([[1, 3, 3],
       [1, 2, 3]])

In [10]:
np.array([1,2,3,4,5],ndmin=2)

array([[1, 2, 3, 4, 5]])

In [11]:
np.array([3,4,5,6,7],dtype=complex)

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [5]:
import numpy as np
print(np.__version__)

1.16.5


In [8]:
import numpy as np

In [10]:
a=np.array([1,2,3])
print(a)

AttributeError: module 'numpy' has no attribute 'max'